/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package ui.swing;

import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JRadioButton;
import ui.KeyGenerator;
import ui.MercuryReference;

/**
 *
 * @author pedro
 */
public class OneOfPanel
	extends AbstractDataPanel
{

	final private String panelName;
	
	static private KeyGenerator keyGenerator = new KeyGenerator ();
	/**
	 * Empty panel key.
	 */
	static private String EMPTY = "empty";
	/** Creates new form OneOfPanel */
	public OneOfPanel (MercuryReference data, UIFrame frame, String panelName)
	{
		super (data, frame);
		this.panelName = panelName;
		initComponents ();
	}

	public void addOption (JRadioButton button, final Object optionValue)
	{
		radioButtonsPanel.add (button);
		button.addActionListener (new ActionListener () {
			@Override
			public void actionPerformed (ActionEvent e) {
				CardLayout cl = (CardLayout) (OneOfPanel.this.optionsPanel.getLayout ());
				cl.show (OneOfPanel.this.optionsPanel, OneOfPanel.EMPTY);
				OneOfPanel.this.data.setValue (optionValue);
			}
		});
		this.buttonGroup.add (button);
	}
	public void addOption (JRadioButton button, final Object optionValue, AbstractDataPanel panel)
	{
		radioButtonsPanel.add (button);
		final String key = OneOfPanel.keyGenerator.nextKey ();
		this.optionsPanel.add (panel, key);
		button.addActionListener (new ActionListener () {
			@Override
			public void actionPerformed (ActionEvent e) {
				CardLayout cl = (CardLayout) (OneOfPanel.this.optionsPanel.getLayout ());
				cl.show (OneOfPanel.this.optionsPanel, key);
				OneOfPanel.this.data.setValue (optionValue);
			}
		});
		this.buttonGroup.add (button);
	}
	
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      buttonGroup = new javax.swing.ButtonGroup();
      radioButtonsPanel = new javax.swing.JPanel();
      optionsPanel = new javax.swing.JPanel();
      emptyLabel = new javax.swing.JLabel();

      setBorder(javax.swing.BorderFactory.createTitledBorder(this.panelName));
      setLayout(new java.awt.BorderLayout());

      radioButtonsPanel.setLayout(new java.awt.GridBagLayout());
      add(radioButtonsPanel, java.awt.BorderLayout.WEST);

      optionsPanel.setLayout(new java.awt.CardLayout());
      optionsPanel.add(emptyLabel, "empty");

      add(optionsPanel, java.awt.BorderLayout.CENTER);
   }// </editor-fold>//GEN-END:initComponents


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.ButtonGroup buttonGroup;
   private javax.swing.JLabel emptyLabel;
   private javax.swing.JPanel optionsPanel;
   private javax.swing.JPanel radioButtonsPanel;
   // End of variables declaration//GEN-END:variables

}
