/*
 * UIPanel.java
 *
 * Created on 18 de Dezembro de 2013, 19:50
 */

package ui.swing;

import ui.Key;
/**
 *
 * @author  pedro
 */
public class UIPanel<D>
	extends DynamicDataPanel<UIPanel<D>, D, DataReference<D> >
{
	/**
	 * Key that this panel is known by the card layout in the {@code UIFrame} dynamic panel.
	 */
	final Key key;
	
	
	/** Creates new form UIPanel */
	UIPanel (UIFrame frame, Key key)
	{
		super (new DataReference<D> (frame), frame);
		//initComponents ();
		this.key = key;
	}
	
	boolean commitValue ()
	{
		for (ComponentPopulate cp : this.componentsPopulate) {
			if (!cp.commitValue ()) {
				return false;
			}
		}
		return true;
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      setLayout(null);
   }// </editor-fold>//GEN-END:initComponents
	
	
   // Variables declaration - do not modify//GEN-BEGIN:variables
   // End of variables declaration//GEN-END:variables

	@Override
	UIPanel getUIPanel ()
	{
		return this;
	}

	@Override
	Key getKey ()
	{
		return this.key;
	}
	
}
